/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufjf.lp3;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author igor
 */
public class JanelaTabela extends javax.swing.JFrame {

   /**
    * Creates new form JanelaTabela
    */
   public JanelaTabela() {
      initComponents();
      DefaultTableModel modelo = (DefaultTableModel) tblNomes.getModel();
      modelo.setDataVector(
              new Object[][]{
                 {"Fulano", "fulano@ufjf.edu.br"},
                 {"Beltrano", "beltrano@ufjf.edu.br"},
                 {"Ciclano", "ciclano@ufjf.edu.br"},},
              new Object[]{
                 "Nome", "e-mail"
              }
      );
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      txtNome = new javax.swing.JTextField();
      btnAdicionar = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblNomes = new javax.swing.JTable();
      txtEmail = new javax.swing.JTextField();
      btnRemover = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Exemplo de Tabela");

      txtNome.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtNomeActionPerformed(evt);
         }
      });

      btnAdicionar.setText("Adicionar");
      btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAdicionarActionPerformed(evt);
         }
      });

      tblNomes.setModel(new DefaultTableModel());
      tblNomes.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblNomesMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(tblNomes);

      txtEmail.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtEmailActionPerformed(evt);
         }
      });

      btnRemover.setText("Remover");
      btnRemover.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRemoverActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(btnAdicionar))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(btnRemover)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnAdicionar)
               .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRemover)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtNomeActionPerformed

   private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
      DefaultTableModel modelo = (DefaultTableModel) tblNomes.getModel();
      if (tblNomes.getSelectedRowCount() > 0) {
         Integer linha = tblNomes.getSelectedRow();
         modelo.setValueAt(txtNome.getText(),linha, 0);
         modelo.setValueAt(txtEmail.getText(),linha, 1);
      } else {
         modelo.addRow(new Object[]{
            txtNome.getText(),
            txtEmail.getText()
         });
      }
      txtNome.setText("");
      txtEmail.setText("");
      txtNome.requestFocus();
      tblNomes.clearSelection();
   }//GEN-LAST:event_btnAdicionarActionPerformed

   private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtEmailActionPerformed

   private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
      DefaultTableModel modelo = (DefaultTableModel) tblNomes.getModel();
      if (tblNomes.getSelectedRowCount() > 0) {
         modelo.removeRow(tblNomes.getSelectedRow());
      }
   }//GEN-LAST:event_btnRemoverActionPerformed

   private void tblNomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNomesMouseClicked
      if (tblNomes.getSelectedRowCount() > 0) {
         DefaultTableModel modelo = (DefaultTableModel) tblNomes.getModel();
         Integer linha = tblNomes.getSelectedRow();
         txtNome.setText((String) modelo.getValueAt(linha, 0));
         txtEmail.setText((String) modelo.getValueAt(linha, 1));
         btnAdicionar.setText("Alterar");
      }else{
         txtNome.setText("");
         txtEmail.setText("");

         btnAdicionar.setText("Adicionar");
      }
   }//GEN-LAST:event_tblNomesMouseClicked

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(JanelaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(JanelaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(JanelaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(JanelaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            JanelaTabela janela = new JanelaTabela();
            janela.setLocationRelativeTo(null);
            janela.setVisible(true);

         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnAdicionar;
   private javax.swing.JButton btnRemover;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable tblNomes;
   private javax.swing.JTextField txtEmail;
   private javax.swing.JTextField txtNome;
   // End of variables declaration//GEN-END:variables
}
